name: test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: Build tests
        run: cmake -S . -B build && cmake --build build
      - name: Run Test
        run: cd build && ctest
